version: "3.8"
services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: mobile-sec-swagger
    ports:
      - "8088:8080"
    environment:
      - SWAGGER_JSON=/api/openapi.yaml
    volumes:
      - ../api/openapi.yaml:/api/openapi.yaml

